import { PlaceholderPage } from "@/components/dashboard/placeholder-page";

export default function RewardsPage() {
  return (
    <PlaceholderPage
      title="Rewards"
      description="Rewards generated by the loyalty engine, their status (available, redeemed, expired), and redemption history."
      plannedFor="Planned for Day 2–3."
    />
  );
}
